### ISSUE TITLE
How to add this project in Nvidia deepstream?

### ISSUE THREAD

**Issue by YagnikThanki** [songdoyouho/LaneNet_TRT#1]
@songdoyouho Can you help me to add this project in Nvidia Deepstream. 
I have read Makefile but it asks for another make.config file path. 
If we can't add it in deep steam how can I run this project individually?

**Comment by songdoyouho** [comment]
Hi YangnikThanki !
I followed TensorRT 4.0.1.6 sample code and added some customized function in this project, 
maybe you can copy this project and compile it as a sample in TensorRT.

Sorry, I don't know how to add this project in to Nvidia Deepstream.

I hope this reply can help you!

**Comment by YagnikThanki** [comment]
@songdoyouho  Thanks. I will test this code with tensorRT.
